// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAE401_API_Vinted.Models.EntityFramework;

#nullable disable

namespace SAE401_API_Vinted.Migrations
{
    [DbContext(typeof(VintedDBContext))]
    partial class VintedDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("AdresseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdresseID"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("adr_libelle");

                    b.Property<int>("VilleID")
                        .HasColumnType("integer")
                        .HasColumnName("vil_id");

                    b.HasKey("AdresseID")
                        .HasName("pk_adr");

                    b.HasIndex("VilleID");

                    b.ToTable("t_e_adresse_adr");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Appartient", b =>
                {
                    b.Property<int>("CompteId")
                        .HasColumnType("integer")
                        .HasColumnName("cob_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("CompteId", "VintieId")
                        .HasName("pk_app");

                    b.HasIndex("VintieId");

                    b.ToTable("t_j_appartient_app");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<int>("CompteurLike")
                        .HasColumnType("integer")
                        .HasColumnName("art_compteurlike");

                    b.Property<DateTime>("DateAjout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("art_dateajout")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("art_description");

                    b.Property<int>("EtatArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("eta_id");

                    b.Property<int>("EtatVenteArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("eva_id");

                    b.Property<int>("MarqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(59)
                        .HasColumnName("mrq_id");

                    b.Property<int>("PrixHT")
                        .HasColumnType("integer")
                        .HasColumnName("art_prixht");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("art_titre");

                    b.Property<int>("VendeurId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_vendeurid");

                    b.HasKey("ArticleId")
                        .HasName("pk_art");

                    b.HasIndex("CategorieId");

                    b.HasIndex("EtatArticleId");

                    b.HasIndex("EtatVenteArticleId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("VendeurId");

                    b.ToTable("t_e_article_art");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("AvisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avs_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvisId"));

                    b.Property<int>("AcheteurId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_acheteurid");

                    b.Property<int>("CodeTypeAvis")
                        .HasColumnType("integer")
                        .HasColumnName("avs_codetypeavis");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("avs_commentaire");

                    b.Property<decimal>("Note")
                        .HasColumnType("numeric")
                        .HasColumnName("avs_note");

                    b.Property<int>("VendeurId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_vendeurid");

                    b.HasKey("AvisId")
                        .HasName("pk_avs");

                    b.HasIndex("AcheteurId");

                    b.HasIndex("CodeTypeAvis");

                    b.HasIndex("VendeurId");

                    b.ToTable("t_e_avis_avs");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.Property<int>("CarteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cab_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarteId"));

                    b.Property<int>("CompteId")
                        .HasColumnType("integer")
                        .HasColumnName("cob_id");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("date")
                        .HasColumnName("cab_dateexpiration");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cab_nom");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("char(16)")
                        .HasColumnName("cab_numero");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cab_prenom");

                    b.HasKey("CarteId")
                        .HasName("pk_cab");

                    b.HasIndex("CompteId");

                    b.ToTable("t_e_cartebancaire_cab");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<int?>("IdParent")
                        .HasColumnType("integer")
                        .HasColumnName("cat_idparent");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cat_libelle");

                    b.HasKey("CategorieId")
                        .HasName("pk_cat");

                    b.HasIndex("IdParent");

                    b.ToTable("t_e_categorie_cat");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("CommandeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommandeID"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<int>("CodeFormat")
                        .HasColumnType("integer")
                        .HasColumnName("fmc_id");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer")
                        .HasColumnName("exp_id");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("cmd_montant_total");

                    b.Property<int?>("PointRelaisID")
                        .HasColumnType("integer")
                        .HasColumnName("ptr_id");

                    b.Property<int>("TypeEnvoiId")
                        .HasColumnType("integer")
                        .HasColumnName("tye_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("CommandeID")
                        .HasName("pk_cmd");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CodeFormat");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("TypeEnvoiId");

                    b.HasIndex("VintieId");

                    b.ToTable("t_e_commande_cmd");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CompteBancaire", b =>
                {
                    b.Property<int>("CompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cob_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompteId"));

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasColumnType("char(27)")
                        .HasColumnName("cob_iban");

                    b.Property<string>("NomTitulaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cob_nomtitulaire");

                    b.Property<string>("PrenomTitulaire")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cob_prenomtitulaire");

                    b.HasKey("CompteId")
                        .HasName("pk_cob");

                    b.ToTable("t_e_comptebancaire_cob");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cnv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<int>("AcheteurId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_idacheteur");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.HasKey("ConversationId")
                        .HasName("pk_cnv");

                    b.HasIndex("AcheteurId");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_e_conversation_cnv");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Couleur", b =>
                {
                    b.Property<int>("CouleurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("clr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CouleurId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("clr_libelle");

                    b.HasKey("CouleurId")
                        .HasName("pk_clr");

                    b.ToTable("t_e_couleur_clr");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CouleurArticle", b =>
                {
                    b.Property<int>("CouleurId")
                        .HasColumnType("integer")
                        .HasColumnName("clr_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.HasKey("CouleurId", "ArticleId")
                        .HasName("pk_cla");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_j_couleurarticle_cla");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.EtatArticle", b =>
                {
                    b.Property<int>("EtatArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtatArticleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("eta_description");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("eta_libelle");

                    b.HasKey("EtatArticleId")
                        .HasName("pk_eta");

                    b.ToTable("t_e_etatarticle_eta");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.EtatVente", b =>
                {
                    b.Property<int>("EtatVenteArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("eva_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtatVenteArticleId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("eva_libelle");

                    b.HasKey("EtatVenteArticleId")
                        .HasName("pk_eva");

                    b.ToTable("t_e_etatventearticle_eva");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Expediteur", b =>
                {
                    b.Property<int>("ExpediteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpediteurId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exp_nom");

                    b.HasKey("ExpediteurId")
                        .HasName("pk_exp");

                    b.ToTable("t_e_expediteur_exp");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Favoris", b =>
                {
                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.HasKey("VintieId", "ArticleId")
                        .HasName("pk_fav");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_j_favoris_fav");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.FormatColis", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fmc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<decimal?>("FraisSupplementaire")
                        .IsRequired()
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("fmc_fraissupplementaire");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("fmc_libelle");

                    b.HasKey("Code")
                        .HasName("pk_fmc");

                    b.ToTable("t_e_formatcolis_fmc");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Horaire", b =>
                {
                    b.Property<int>("PointRelaisID")
                        .HasColumnType("integer")
                        .HasColumnName("ptr_id");

                    b.Property<int>("JourId")
                        .HasColumnType("integer")
                        .HasColumnName("jor_id");

                    b.Property<TimeSpan>("HeureFermeture")
                        .HasColumnType("time")
                        .HasColumnName("hor_heurefermeture");

                    b.Property<TimeSpan>("HeureOuverture")
                        .HasColumnType("time")
                        .HasColumnName("hor_heureouverture");

                    b.HasKey("PointRelaisID", "JourId")
                        .HasName("pk_hor");

                    b.HasIndex("JourId");

                    b.ToTable("t_j_horaire_hor");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("img_url");

                    b.HasKey("ImageId")
                        .HasName("pk_img");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_e_image_img");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Jour", b =>
                {
                    b.Property<int>("JourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("jor_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JourId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("jor_libelle");

                    b.HasKey("JourId")
                        .HasName("pk_jor");

                    b.ToTable("t_e_jour_jor");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Marque", b =>
                {
                    b.Property<int>("MarqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mrq_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarqueId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mrq_libelle");

                    b.HasKey("MarqueId")
                        .HasName("pk_mrq");

                    b.ToTable("t_e_marque_mrq");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Matiere", b =>
                {
                    b.Property<int>("MatiereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MatiereId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("mat_libelle");

                    b.HasKey("MatiereId")
                        .HasName("pk_mat");

                    b.ToTable("t_e_matiere_mat");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.MatiereArticle", b =>
                {
                    b.Property<int>("MatiereId")
                        .HasColumnType("integer")
                        .HasColumnName("mat_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.HasKey("MatiereId", "ArticleId")
                        .HasName("pk_mar");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_j_matierearticle_mar");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("msg_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("msg_contenu");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("cnv_id");

                    b.Property<DateTime?>("DateEnvoi")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("msg_dateenvoi")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer")
                        .HasColumnName("msg_idexpediteur");

                    b.HasKey("MessageId")
                        .HasName("pk_msg");

                    b.HasIndex("ConversationId");

                    b.ToTable("t_e_message_msg");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.MotifSignalement", b =>
                {
                    b.Property<int>("MotifSignalementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("mos_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MotifSignalementId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mos_libelle");

                    b.HasKey("MotifSignalementId")
                        .HasName("pk_mos");

                    b.ToTable("t_e_motifsignalement_mos");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Pays", b =>
                {
                    b.Property<int>("PaysId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pay_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaysId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pay_libelle");

                    b.HasKey("PaysId")
                        .HasName("pk_pay");

                    b.ToTable("t_e_pays_pay");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.PointRelais", b =>
                {
                    b.Property<int>("PointRelaisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ptr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PointRelaisID"));

                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ptr_nom");

                    b.HasKey("PointRelaisID")
                        .HasName("pk_ptr");

                    b.HasIndex("AdresseId");

                    b.ToTable("t_e_pointrelais_ptr");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.PointRelaisFavoris", b =>
                {
                    b.Property<int>("PointRelaisId")
                        .HasColumnType("integer")
                        .HasColumnName("ptr_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("PointRelaisId", "VintieId")
                        .HasName("pk_prf");

                    b.HasIndex("VintieId");

                    b.ToTable("t_j_pointrelaisfavoris_prf");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Possede", b =>
                {
                    b.Property<int>("CodeType")
                        .HasColumnType("integer")
                        .HasColumnName("tad_id");

                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    b.HasKey("CodeType", "AdresseId")
                        .HasName("pk_psd");

                    b.HasIndex("AdresseId");

                    b.ToTable("t_j_possede_psd");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Preference", b =>
                {
                    b.Property<int>("ExpediteurId")
                        .HasColumnType("integer")
                        .HasColumnName("exp_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("ExpediteurId", "VintieId")
                        .HasName("pk_pre");

                    b.HasIndex("VintieId");

                    b.ToTable("t_j_preference_pre");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Reside", b =>
                {
                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("adr_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("AdresseId", "VintieId")
                        .HasName("pk_rsd");

                    b.HasIndex("VintieId");

                    b.ToTable("t_j_reside_rsd");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Retour", b =>
                {
                    b.Property<int>("RetourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ret_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetourId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<DateTime?>("DateConfirmation")
                        .HasColumnType("date")
                        .HasColumnName("ret_dateconfirmation");

                    b.Property<DateTime?>("DateDemande")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("ret_datedemande")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("date")
                        .HasColumnName("ret_dateenvoi");

                    b.Property<double>("Frais")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("ret_frais");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ret_motif");

                    b.Property<int>("StatusRetourId")
                        .HasColumnType("integer")
                        .HasColumnName("str_id");

                    b.Property<int>("TypeRetourId")
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("RetourId")
                        .HasName("pk_ret");

                    b.HasIndex("ArticleId");

                    b.HasIndex("StatusRetourId");

                    b.HasIndex("TypeRetourId");

                    b.HasIndex("VintieId");

                    b.ToTable("t_e_retour_ret");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Signalement", b =>
                {
                    b.Property<int>("SignalementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sgn_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SignalementId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("sgn_commentaire");

                    b.Property<DateTime?>("DateFermetureTicket")
                        .HasColumnType("date")
                        .HasColumnName("sgn_datefermetureticket");

                    b.Property<DateTime>("DateOuvertureTicket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("sgn_dateouvertureticket")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("MotifSignalementId")
                        .HasColumnType("integer")
                        .HasColumnName("mos_id");

                    b.Property<int>("StatusSignalementId")
                        .HasColumnType("integer")
                        .HasColumnName("sts_id");

                    b.Property<int>("VintieId")
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    b.HasKey("SignalementId")
                        .HasName("pk_sgn");

                    b.HasIndex("ArticleId");

                    b.HasIndex("MotifSignalementId");

                    b.HasIndex("StatusSignalementId");

                    b.HasIndex("VintieId");

                    b.ToTable("t_e_signalement_sgn");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusOffre", b =>
                {
                    b.Property<int>("StatusOffreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusOffreId"));

                    b.Property<string>("StatusOffreLibelle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sto_libelle");

                    b.HasKey("StatusOffreId")
                        .HasName("pk_sto");

                    b.ToTable("t_e_statusoffre_sto");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusRetour", b =>
                {
                    b.Property<int>("StatusRetourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("str_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusRetourId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("str_libelle");

                    b.HasKey("StatusRetourId")
                        .HasName("pk_str");

                    b.ToTable("t_e_statusretour_str");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusSignalement", b =>
                {
                    b.Property<int>("StatusSignalementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sts_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusSignalementId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sts_libelle");

                    b.HasKey("StatusSignalementId")
                        .HasName("pk_sts");

                    b.ToTable("t_e_statussignalement_sts");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Taille", b =>
                {
                    b.Property<int>("TailleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TailleId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tal_libelle");

                    b.Property<int>("TypeTailleId")
                        .HasColumnType("integer")
                        .HasColumnName("tta_id");

                    b.HasKey("TailleId")
                        .HasName("pk_tal");

                    b.HasIndex("TypeTailleId");

                    b.ToTable("t_e_taille_tal");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TailleArticle", b =>
                {
                    b.Property<int>("TailleId")
                        .HasColumnType("integer")
                        .HasColumnName("tal_id");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer")
                        .HasColumnName("art_id");

                    b.HasKey("TailleId", "ArticleId")
                        .HasName("pk_tar");

                    b.HasIndex("ArticleId");

                    b.ToTable("t_j_taillearticle_tar");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tsc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionID"));

                    b.Property<int>("CommandeID")
                        .HasColumnType("integer")
                        .HasColumnName("tsc_idcommande");

                    b.Property<DateTime>("DateTransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("tsc_datetransaction")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("StatusTransaction")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tsc_statustransaction");

                    b.HasKey("TransactionID")
                        .HasName("pk_tsc");

                    b.HasIndex("CommandeID");

                    b.ToTable("t_e_transaction_tsc");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeAdresse", b =>
                {
                    b.Property<int>("TypeAdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tad_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeAdresseId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tad_libelle");

                    b.HasKey("TypeAdresseId")
                        .HasName("pk_tad");

                    b.ToTable("t_e_typeadresse_tad");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeAvis", b =>
                {
                    b.Property<int>("TypeAvisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tas_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeAvisID"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tas_libelle");

                    b.HasKey("TypeAvisID")
                        .HasName("pk_tas");

                    b.ToTable("t_e_typeavis_tas");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeCompte", b =>
                {
                    b.Property<int>("TypeCompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tyc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeCompteId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tyc_libelle");

                    b.HasKey("TypeCompteId")
                        .HasName("pk_tyc");

                    b.ToTable("t_e_typecompte_tyc");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeEnvoi", b =>
                {
                    b.Property<int>("TypeEnvoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tye_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeEnvoiId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tye_libelle");

                    b.HasKey("TypeEnvoiId")
                        .HasName("pk_tye");

                    b.ToTable("t_e_typeenvoi_tye");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeRetour", b =>
                {
                    b.Property<int>("TypeRetourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeRetourId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tpr_libelle");

                    b.HasKey("TypeRetourId")
                        .HasName("pk_tpr");

                    b.ToTable("t_e_typeretour_tpr");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeTaille", b =>
                {
                    b.Property<int>("TypeTailleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeTailleId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("cat_id");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tta_libelle");

                    b.HasKey("TypeTailleId")
                        .HasName("pk_tta");

                    b.HasIndex("CategorieId");

                    b.ToTable("t_e_typetaille_tta");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Ville", b =>
                {
                    b.Property<int>("VilleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vil_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VilleId"));

                    b.Property<int>("CodePostal")
                        .HasColumnType("char(5)")
                        .HasColumnName("vil_codepostal");

                    b.Property<float?>("Latitude")
                        .HasColumnType("numeric(15,13)")
                        .HasColumnName("vil_latitude");

                    b.Property<float?>("Longitude")
                        .HasColumnType("numeric(15,13)")
                        .HasColumnName("vil_longitude");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("vil_nom");

                    b.Property<int>("PaysId")
                        .HasColumnType("integer")
                        .HasColumnName("pay_id");

                    b.HasKey("VilleId")
                        .HasName("pk_vil");

                    b.HasIndex("PaysId");

                    b.ToTable("t_e_ville_vil");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Vintie", b =>
                {
                    b.Property<int>("VintieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vnt_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VintieId"));

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasColumnType("Char(1)")
                        .HasColumnName("vnt_civilite");

                    b.Property<bool>("Consentement")
                        .HasColumnType("boolean")
                        .HasColumnName("vnt_consentement");

                    b.Property<DateTime>("DateDerniereConnexion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("vnt_datederniereconnexion")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DateInscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("vnt_dateinscription")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DateNaissance")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("vnt_datenaissance");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("vnt_mail");

                    b.Property<double>("MontantCompte")
                        .HasColumnType("numeric")
                        .HasColumnName("vnt_montantcompte");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vnt_nom");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vnt_prenom");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vnt_pseudo");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vnt_pwd");

                    b.Property<string>("Siret")
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)")
                        .HasColumnName("vnt_siret");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("Char(14)")
                        .HasColumnName("vnt_telephone");

                    b.Property<int>("TypeCompteId")
                        .HasColumnType("integer")
                        .HasColumnName("tyc_id");

                    b.Property<string>("URLPhoto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("vnt_urlphoto");

                    b.HasKey("VintieId")
                        .HasName("pk_vnt");

                    b.HasIndex("TypeCompteId");

                    b.HasIndex(new[] { "Mail" }, "uq_vnt_mail")
                        .IsUnique();

                    b.ToTable("t_e_vintie_vnt");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Offre", b =>
                {
                    b.HasBaseType("SAE401_API_Vinted.Models.EntityFramework.Message");

                    b.Property<double>("Montant")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("ofr_montant");

                    b.Property<int>("StatusOffreId")
                        .HasColumnType("integer")
                        .HasColumnName("sto_id");

                    b.HasIndex("StatusOffreId");

                    b.ToTable("t_e_offre_ofr");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Adresse", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Ville", "VilleAdresse")
                        .WithMany("AdressesVilles")
                        .HasForeignKey("VilleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adr_vil");

                    b.Navigation("VilleAdresse");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Appartient", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.CompteBancaire", "CompteIdNavigation")
                        .WithMany("AppartientCompte")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_cob");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintieIdNavigation")
                        .WithMany("AppartienentVintie")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_vnt");

                    b.Navigation("CompteIdNavigation");

                    b.Navigation("VintieIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Article", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Categorie", "CategorieDeArticle")
                        .WithMany("CategoriesArticles")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_art_cat");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.EtatArticle", "EtatDeArticle")
                        .WithMany("EtatsDesArticles")
                        .HasForeignKey("EtatArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_art_eta");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.EtatVente", "EtatVenteDeArticle")
                        .WithMany("EtatsVenteDesArticles")
                        .HasForeignKey("EtatVenteArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_art_eva");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Marque", "MarqueDeArticle")
                        .WithMany("MarquesDesArticles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_art_mrq");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VendeurDeArticle")
                        .WithMany("ArticlesDuVendeur")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_art_vnt");

                    b.Navigation("CategorieDeArticle");

                    b.Navigation("EtatDeArticle");

                    b.Navigation("EtatVenteDeArticle");

                    b.Navigation("MarqueDeArticle");

                    b.Navigation("VendeurDeArticle");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "APourAcheteur")
                        .WithMany("ADesAvisAcheteur")
                        .HasForeignKey("AcheteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avs_acheteurvnt");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeAvis", "APourTypeAvis")
                        .WithMany("PossedesTypeAvis")
                        .HasForeignKey("CodeTypeAvis")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avs_tas");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "APourVendeur")
                        .WithMany("ADesAvisVendeur")
                        .HasForeignKey("VendeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avs_vendeurvnt");

                    b.Navigation("APourAcheteur");

                    b.Navigation("APourTypeAvis");

                    b.Navigation("APourVendeur");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CarteBancaire", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.CompteBancaire", "CompteIdNavigation")
                        .WithMany("CartesCompte")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cab_cob");

                    b.Navigation("CompteIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Categorie", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Categorie", "CategorieParentIdNavigation")
                        .WithMany("CategoriesParent")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cat_cat");

                    b.Navigation("CategorieParentIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleCommande")
                        .WithMany("CommandesArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.FormatColis", "ACommeFormat")
                        .WithMany("ADesCommandes")
                        .HasForeignKey("CodeFormat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_fmc");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.PointRelais", "ACommePointRelais")
                        .WithMany("ADesCommandes")
                        .HasForeignKey("CodeFormat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_ptr");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Expediteur", "ExpediteurCommande")
                        .WithMany("CommandesExpediteurs")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_exp");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeEnvoi", "TypeEnvoiDeCommande")
                        .WithMany("TypeEnvoiCommandes")
                        .HasForeignKey("TypeEnvoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_tye");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintieCommande")
                        .WithMany("CommandesVinties")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_vnt");

                    b.Navigation("ACommeFormat");

                    b.Navigation("ACommePointRelais");

                    b.Navigation("ArticleCommande");

                    b.Navigation("ExpediteurCommande");

                    b.Navigation("TypeEnvoiDeCommande");

                    b.Navigation("VintieCommande");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Conversation", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "AcheteurIdNavigation")
                        .WithMany("ConversationsAcheteur")
                        .HasForeignKey("AcheteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cnv_acheteurvnt");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleIdNavigation")
                        .WithMany("ConversationsArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cnv_art");

                    b.Navigation("AcheteurIdNavigation");

                    b.Navigation("ArticleIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CouleurArticle", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleConcerne")
                        .WithMany("CouleursArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cla_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Couleur", "CouleurConcernee")
                        .WithMany("CouleursDesArticles")
                        .HasForeignKey("CouleurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cla_clr");

                    b.Navigation("ArticleConcerne");

                    b.Navigation("CouleurConcernee");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Favoris", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "EstFavoris")
                        .WithMany("FavorisArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fav_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "FavorisVintie")
                        .WithMany("FavorisDeVintie")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fav_vnt");

                    b.Navigation("EstFavoris");

                    b.Navigation("FavorisVintie");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Horaire", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Jour", "JourOuvert")
                        .WithMany("HeuresOuverts")
                        .HasForeignKey("JourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hor_jor");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.PointRelais", "ACommeHoraire")
                        .WithMany("HorairesPointRelais")
                        .HasForeignKey("PointRelaisID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hor_ptr");

                    b.Navigation("ACommeHoraire");

                    b.Navigation("JourOuvert");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Image", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleDeImage")
                        .WithMany("ImagesDeArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_img_art");

                    b.Navigation("ArticleDeImage");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.MatiereArticle", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleMatiere")
                        .WithMany("ArticlesMatieres")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mar_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Matiere", "MatiereDeArticle")
                        .WithMany("MatieresDesArticles")
                        .HasForeignKey("MatiereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mar_mat");

                    b.Navigation("ArticleMatiere");

                    b.Navigation("MatiereDeArticle");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Message", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Conversation", "ConversationMessage")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_msg_cnv");

                    b.Navigation("ConversationMessage");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.PointRelais", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Adresse", "AdressePointRelais")
                        .WithMany("ADesPointRelais")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ptr_adr");

                    b.Navigation("AdressePointRelais");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.PointRelaisFavoris", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.PointRelais", "FavPointRelais")
                        .WithMany("PointsRelaisEnFavoris")
                        .HasForeignKey("PointRelaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prf_ptr");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintiePointRelais")
                        .WithMany("PointRelaisFavorisVintie")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_prf_vnt");

                    b.Navigation("FavPointRelais");

                    b.Navigation("VintiePointRelais");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Possede", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Adresse", "APourAdresse")
                        .WithMany("PossedesAdresse")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_psd_adr");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeAdresse", "APourType")
                        .WithMany("PossedesType")
                        .HasForeignKey("CodeType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_psd_tad");

                    b.Navigation("APourAdresse");

                    b.Navigation("APourType");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Preference", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Expediteur", "ExpediteurIdNavigation")
                        .WithMany("PreferencesExpediteur")
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_exp");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintieIdNavigation")
                        .WithMany("PreferencesVintie")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pre_vnt");

                    b.Navigation("ExpediteurIdNavigation");

                    b.Navigation("VintieIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Reside", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Adresse", "ResideA")
                        .WithMany("AResidents")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsd_adr");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "ResideVintie")
                        .WithMany("VintiesResides")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsd_vnt");

                    b.Navigation("ResideA");

                    b.Navigation("ResideVintie");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Retour", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleRetourne")
                        .WithMany("RetourDesArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ret_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.StatusRetour", "StatusDuRetour")
                        .WithMany("StatusDesRetours")
                        .HasForeignKey("StatusRetourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ret_str");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeRetour", "TypeDuRetour")
                        .WithMany("TypesDesRetours")
                        .HasForeignKey("TypeRetourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ret_tpr");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintieRetour")
                        .WithMany("RetourDesVintie")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ret_vnt");

                    b.Navigation("ArticleRetourne");

                    b.Navigation("StatusDuRetour");

                    b.Navigation("TypeDuRetour");

                    b.Navigation("VintieRetour");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Signalement", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleDuSignalement")
                        .WithMany("SignalementsDeArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sgn_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.MotifSignalement", "MotifDuSignalement")
                        .WithMany("MotifsDesSignalement")
                        .HasForeignKey("MotifSignalementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sgn_mos");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.StatusSignalement", "StatusDuSignalement")
                        .WithMany("StatusDesSignalements")
                        .HasForeignKey("StatusSignalementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sgn_sts");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Vintie", "VintieSignalant")
                        .WithMany("SignalementsDeArticle")
                        .HasForeignKey("VintieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sgn_vnt");

                    b.Navigation("ArticleDuSignalement");

                    b.Navigation("MotifDuSignalement");

                    b.Navigation("StatusDuSignalement");

                    b.Navigation("VintieSignalant");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Taille", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeTaille", "TypeTailleIdNavigation")
                        .WithMany("TaillesTypeTaille")
                        .HasForeignKey("TypeTailleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tal_tta");

                    b.Navigation("TypeTailleIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TailleArticle", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Article", "ArticleIdNavigation")
                        .WithMany("TaillesArticle")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tar_art");

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Taille", "TailleIdNavigation")
                        .WithMany("ArticlesTaille")
                        .HasForeignKey("TailleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tar_tal");

                    b.Navigation("ArticleIdNavigation");

                    b.Navigation("TailleIdNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Commande", "CommandeTransaction")
                        .WithMany("TransactionsCommandes")
                        .HasForeignKey("CommandeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tsc_cmd");

                    b.Navigation("CommandeTransaction");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeTaille", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Categorie", "CategorieTypeTaille")
                        .WithMany("TypesTaillesCategories")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieTypeTaille");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Ville", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Pays", "PaysVille")
                        .WithMany("VillesPays")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vil_pay");

                    b.Navigation("PaysVille");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Vintie", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.TypeCompte", "VintieCodeNavigation")
                        .WithMany("VintiesType")
                        .HasForeignKey("TypeCompteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vnt_tyc");

                    b.Navigation("VintieCodeNavigation");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Offre", b =>
                {
                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.Message", null)
                        .WithOne()
                        .HasForeignKey("SAE401_API_Vinted.Models.EntityFramework.Offre", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SAE401_API_Vinted.Models.EntityFramework.StatusOffre", "EstStatusOffre")
                        .WithMany("StatusOffres")
                        .HasForeignKey("StatusOffreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ofr_sto");

                    b.Navigation("EstStatusOffre");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("ADesPointRelais");

                    b.Navigation("AResidents");

                    b.Navigation("PossedesAdresse");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Article", b =>
                {
                    b.Navigation("ArticlesMatieres");

                    b.Navigation("CommandesArticles");

                    b.Navigation("ConversationsArticle");

                    b.Navigation("CouleursArticle");

                    b.Navigation("FavorisArticle");

                    b.Navigation("ImagesDeArticle");

                    b.Navigation("RetourDesArticles");

                    b.Navigation("SignalementsDeArticle");

                    b.Navigation("TaillesArticle");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Categorie", b =>
                {
                    b.Navigation("CategoriesArticles");

                    b.Navigation("CategoriesParent");

                    b.Navigation("TypesTaillesCategories");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Commande", b =>
                {
                    b.Navigation("TransactionsCommandes");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.CompteBancaire", b =>
                {
                    b.Navigation("AppartientCompte");

                    b.Navigation("CartesCompte");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Couleur", b =>
                {
                    b.Navigation("CouleursDesArticles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.EtatArticle", b =>
                {
                    b.Navigation("EtatsDesArticles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.EtatVente", b =>
                {
                    b.Navigation("EtatsVenteDesArticles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Expediteur", b =>
                {
                    b.Navigation("CommandesExpediteurs");

                    b.Navigation("PreferencesExpediteur");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.FormatColis", b =>
                {
                    b.Navigation("ADesCommandes");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Jour", b =>
                {
                    b.Navigation("HeuresOuverts");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Marque", b =>
                {
                    b.Navigation("MarquesDesArticles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Matiere", b =>
                {
                    b.Navigation("MatieresDesArticles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.MotifSignalement", b =>
                {
                    b.Navigation("MotifsDesSignalement");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Pays", b =>
                {
                    b.Navigation("VillesPays");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.PointRelais", b =>
                {
                    b.Navigation("ADesCommandes");

                    b.Navigation("HorairesPointRelais");

                    b.Navigation("PointsRelaisEnFavoris");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusOffre", b =>
                {
                    b.Navigation("StatusOffres");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusRetour", b =>
                {
                    b.Navigation("StatusDesRetours");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.StatusSignalement", b =>
                {
                    b.Navigation("StatusDesSignalements");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Taille", b =>
                {
                    b.Navigation("ArticlesTaille");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeAdresse", b =>
                {
                    b.Navigation("PossedesType");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeAvis", b =>
                {
                    b.Navigation("PossedesTypeAvis");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeCompte", b =>
                {
                    b.Navigation("VintiesType");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeEnvoi", b =>
                {
                    b.Navigation("TypeEnvoiCommandes");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeRetour", b =>
                {
                    b.Navigation("TypesDesRetours");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.TypeTaille", b =>
                {
                    b.Navigation("TaillesTypeTaille");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Ville", b =>
                {
                    b.Navigation("AdressesVilles");
                });

            modelBuilder.Entity("SAE401_API_Vinted.Models.EntityFramework.Vintie", b =>
                {
                    b.Navigation("ADesAvisAcheteur");

                    b.Navigation("ADesAvisVendeur");

                    b.Navigation("AppartienentVintie");

                    b.Navigation("ArticlesDuVendeur");

                    b.Navigation("CommandesVinties");

                    b.Navigation("ConversationsAcheteur");

                    b.Navigation("FavorisDeVintie");

                    b.Navigation("PointRelaisFavorisVintie");

                    b.Navigation("PreferencesVintie");

                    b.Navigation("RetourDesVintie");

                    b.Navigation("SignalementsDeArticle");

                    b.Navigation("VintiesResides");
                });
#pragma warning restore 612, 618
        }
    }
}
